name: Rust Project Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Verify Rust installation
      run: |
        rustc --version
        cargo --version

    - name: Build
      run: cargo build --release

    - name: Check if crate version exists on crates.io
      id: check_version
      run: ./check_version.sh

    - name: Login in crates.io
      if: steps.check_version.outcome == 'success'
      run: cargo login ${{secrets.CRATES_API_TOKEN}}

    - name: Publish to crates.io
      if: steps.check_version.outcome == 'success'
      run: cargo publish
