name: Rust Project Artifact

on:
  push:
    branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: install rust
      run: |
        curl https://sh.rustup.rs -sSf | sh
        rustc --version
        cargo --version

    - name: Build
      run: cargo build --release

    - name: Login in crates.io
      run: cargo login ${{secrets.CRATES_API_TOKEN}}

    - name: Publish to crates.io
      run: cargo publish
