name: Rust Project Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Verify Rust installation
      run: |
        ls -la
        rustc --version
        cargo --version

    - name: Build
      run: |
        ls -la
        cargo build --release
        ls -la

    - name: Check if crate version exists on crates.io
      id: check_version
      run: |
        ls -la 
        ./check_version.sh

    - name: Running Built Artifact
      run: ./target/release/
      
    - name: Login in crates.io
      run: cargo login ${{secrets.CRATES_API_TOKEN}}

    - name: Publish to crates.io
      run: cargo publish
